### ISSUE TITLE
backward issue

### ISSUE THREAD

**Issue by GongweiChen** [Nate1874/StructPool#1]
https://github.com/Nate1874/StructPool/blob/2a484ab22bea8a51de97840b538a56c9f60dce50/pool.py#L82
Thanks for the work! I have one issue about the backward propagation of gradients in pooling layer.
The _equal_ operation doesn't have backward function, how to compute the gradients w.r.t. "w_filter" and "w_compat"?

**Comment by Nate1874** [comment]
Thanks for pointing out.
I think you can use the current version and treat w_filter as pre-defined compatibility function.
Otherwise, to enable the back-propagation for w_filter, we can multiply the max of L to X for computing the X_out.
